[project]
name = "fastapi-hw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alexandr Belov", email = "aleksandr.b.dev-f@innofin.team" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.141.1",
    "psycopg2-binary>=2.9.13",
    "pydantic>=2.13.5",
    "pyjwt>=2.14.0",
    "sqlalchemy[asyncio]>=2.0.52",
]

[project.scripts]
fastapi-hw = "fastapi_hw:main"

[tool.uv]
package = false

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.5",
]
