"""add user name

Revision ID: f02000f0bc17
Revises: 80cf8efde307
Create Date: 2026-09-15 20:53:13.242976

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f02000f0bc17"
down_revision: Union[str, Sequence[str], None] = "80cf8efde307"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column("name", sa.String(length=255), nullable=True),
    )

    op.execute(sa.text("UPDATE users SET name = 'Пользователь' WHERE name IS NULL"))

    op.alter_column("users", "name", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "name")
    # ### end Alembic commands ###
